development:
  host: localhost
  port: 27017
  database: document_editor_dev2
  logfile: development.log
    
production:
  host: localhost
  port: 27017
  database: document_editor_prod
  logfile: production.log
    
environment: development
